language: cpp
sudo: required

compiler:
  - clang

os:
  - linux
  # - osx

before_install:
  - sh travis/install-deps-${TRAVIS_OS_NAME}.sh

script:
  - cd build
  - cmake ..
  - make
  - cd ..
  - sh travis/run-tests.sh
